# Generated by Django 4.1.7 on 2023-07-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='created',
        ),
    ]
